
#! groovy 

pipeline {

  //Option 1: Available pod templates: k8s-build, k8s-dind

  //Ref : https://confluence.app.alcatel-lucent.com/display/AACTODEVOPS/Getting+started+with+Kubernetes#GettingstartedwithKubernetes-Whatisa'podtemplate'?

  //Option 2: Customize the pod template 

  //Ref : https://confluence.app.alcatel-lucent.com/display/AACTODEVOPS/K8s+Multi-Container+Declarative+Pipeline+Updates

  agent { label 'k8s-build' }

  options {

    //Timeout period for the Pipeline run, after which Jenkins should abort the Pipeline

    timeout(time: 15, unit: 'MINUTES')

    //Persist artifacts and console output for the specific number of days

    buildDiscarder(logRotator(daysToKeepStr: '7', artifactDaysToKeepStr: '0'))

    //Disallow concurrent executions of the Pipeline, preventing simultaneous accesses to shared resources

    disableConcurrentBuilds()

    //Prepend all console output generated by the Pipeline run with the time at which the line was emitted

    timestamps()

  }

  parameters {

   // Build parameters

  }

  stages {

    stage('Build') {

      steps {

        // Build your software somehow

      }

    }

    stage('Publish') {

      steps {

        // Use Artifactory plugin to publish artifacts to Artifactory

      }

    }

    stage('Test') {

      steps {

        // Provision a test environment and run acceptance tests

      }

    }

  }

  post {

    always {

      cleanWs()

    }

    success {

    }

    failure {

    }

    changed {

      // Only run if the current Pipeline run has a different status from the previously completed Pipeline

    }

    unstable {

    }

  }

}
